#include <stdlib.h>
#include "precedence.h"

ParseRule rules[] = {
  [END_OF_FILE] = {NULL, NULL, ZERO_PRECEDENCE},
  [TOKEN_ERROR] = {NULL, NULL, ZERO_PRECEDENCE},
  [L_IDENTIFIER] = {NULL, NULL, ZERO_PRECEDENCE},
  [L_STRING] = {NULL, NULL, ZERO_PRECEDENCE},
  [L_FLOAT] = {number, NULL, ZERO_PRECEDENCE},
  [S_STAR] = {NULL, binary, FACTOR_PRECEDENCE},
  [S_SLASH] = {NULL, binary, FACTOR_PRECEDENCE},
  [S_MINUS] = {unary, binary, SUM_PRECEDENCE},
  [S_PLUS] = {NULL, binary, SUM_PRECEDENCE},
  [S_LEFT_PARENTHESIS] = {grouping, NULL, ZERO_PRECEDENCE},
  [S_RIGHT_PARENTHESIS] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_LEFT_CURLYBRACE] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_RIGHT_CURLYBRACE] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_COMMA] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_DOT] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_SEMICOLON] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_BANG] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_GREATER] = {NULL, NULL, ZERO_PRECEDENCE},
  [S_LESS] = {NULL, NULL, ZERO_PRECEDENCE},
  [D_BANG_TILDE] = {NULL, NULL, ZERO_PRECEDENCE},
  [D_EQUAL] = {NULL, NULL, ZERO_PRECEDENCE},
  [D_GREATER_EQUAL] = {NULL, NULL, ZERO_PRECEDENCE},
  [D_LESS_EQUAL] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_AND] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_BUILD] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_DEFINE] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_ELSE] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_END] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_JOIN] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_OR] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_RETURN] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_SELF] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_FALSE] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_TRUE] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_UNLESS] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_UNTIL] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_VOID] = {NULL, NULL, ZERO_PRECEDENCE}, 
  [K_WHILE] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_XOR] = {NULL, NULL, ZERO_PRECEDENCE},
  [K_YIELD] = {NULL, NULL, ZERO_PRECEDENCE},
};

static ParseRule* getRule(TokenType token) {
  return &rules[token];
}
